# Site settings
name: Less Or More
email: 371148968@qq.com
author: ying zhao
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/qq371148968
baseurl: "/blog"
description: Actually, less is more! zhaoying
meta_description: ZHAOYING;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qq371148968

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

